version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3007:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Prevents node_modules reinstallation
    command: ["npm", "start"]
    depends_on:
      - api-gateway
    networks:
      - app-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "8081:8080" # Maps external port 8081 to internal port 8080 (API Gateway)
    depends_on:
      - event-service
      - guest-service
      - vendor-service
      - budget-service
      - task-service
      - notification-service
    networks:
      - app-network

  event-service:
    build: ./services/event-management
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/eventdb
    depends_on:
      - mongo
    networks:
      - app-network

  guest-service:
    build: ./services/guest-management
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/guestdb
    depends_on:
      - mongo
    networks:
      - app-network

  vendor-service:
    build: ./services/vendor-scheduling
    ports:
      - "3003:3003"
    environment:
      - MONGO_URI=mongodb://mongo:27017/vendordb
    depends_on:
      - mongo
    networks:
      - app-network

  budget-service:
    build: ./services/budget-tracking
    ports:
      - "3004:3004"
    environment:
      - MONGO_URI=mongodb://mongo:27017/budgetdb
    depends_on:
      - mongo
    networks:
      - app-network

  task-service:
    build: ./services/task-management
    ports:
      - "3005:3005"
    environment:
      - MONGO_URI=mongodb://mongo:27017/taskdb
    depends_on:
      - mongo
    networks:
      - app-network

  notification-service:
    build: ./services/notification
    ports:
      - "3006:3006"
    environment:
      - MONGO_URI=mongodb://mongo:27017/notificationdb
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
